data:
  dir: /workspace/Data/land_cover_new_crop/Dataset/256
  name: landcover
loss:
  eps: 1.0e-06
  from_logits: true
  ignore_index: 255
  smoothing_factor: 0.1
  log_loss: true
  mode: multiclass
  name: CrossEntropyLoss
  smooth: 0.1
model: 
  activation: softmax
  dropout: 0.5
  encoder_name: resnet101
  encoder_weights: imagenet
  model_name: DeepLabV3Plus
  pooling: max
test_evaluation:
  dir: /home/oury/Documents/Segmentation_Project/Data/land_cover/test
  model_name: null
  save_dir: null
train: 
  back_epochs: 10
  batch_size: 32
  check_convergence_epslion: 0.0001
  desirable_class: 7
  lr: 0.001
  num_epochs: 80
  optimizer_name: AdamW
  weight_decay: 0.04
transformes:
  types:
    ColorJitter: True 
    horizontal_flip: True 
    vertical_flip: True 


